# Generated by Django 5.0.4 on 2024-04-29 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HighrisePlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30)),
                ('is_scam', models.BooleanField(default=False)),
                ('telegram_id', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BotModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=30)),
                ('room_id', models.CharField(max_length=30)),
                ('welcome', models.BooleanField(default=True)),
                ('set_welcome', models.TextField(default='Добро пожаловать!')),
                ('warnmode', models.CharField(choices=[('mute', 'Mute'), ('ban', 'Ban'), ('kick', 'Kick')], default='mute', max_length=10)),
                ('warnlimit', models.IntegerField(default=3)),
                ('warntime', models.IntegerField(default=24)),
                ('defaultfilter', models.BooleanField(default=True)),
                ('ignoreword', models.TextField(blank=True)),
                ('filter', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('banned_users', models.ManyToManyField(related_name='banned_by_bots', to='API.highriseplayers')),
            ],
        ),
    ]
