# Generated by Django 5.0.4 on 2024-04-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_highriseplayers_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmoderator',
            name='api_key',
            field=models.CharField(max_length=64),
        ),
    ]
