# Generated by Django 5.0.4 on 2024-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_botmoderator_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmoderator',
            name='mute_duration',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
    ]
