# Generated by Django 5.0.4 on 2024-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_botmoderator_mute_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmoderator',
            name='mute_duration',
            field=models.IntegerField(default=24),
        ),
    ]
