# Generated by Django 5.0.4 on 2024-05-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_botmoderator_mute_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botmoderator',
            old_name='filter',
            new_name='filter_words',
        ),
        migrations.RenameField(
            model_name='botmoderator',
            old_name='ignoreword',
            new_name='ignorewords',
        ),
    ]
